[Distribution]
Distribution=centos
Release=10

[Output]
Format=disk

[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=@core
         azure-vm-utils
         chrony
         cloud-init
         cloud-utils-growpart
		 curl
         dosfstools
         hyperv-daemons
		 less
         NetworkManager
         NetworkManager-cloud-setup
		 openssh-server
		 systemd
         systemd-boot-unsigned
		 tar
         udev
		 vim-minimal
         WALinuxAgent
         xfsprogs
KernelModulesInitrdInclude=default
                          hyperv
KernelModulesInitrdExclude=.*
KernelCommandLine=console=tty0
                  console=ttyS0,115200n8
                  selinux=0
                  systemd.firstboot=no

[Build]
ToolsTree=default
ToolsTreeDistribution=fedora

