name: Test image build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - "self-hosted"
      - "centos"
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Build kernel and image
        uses: ./
        id: build
        with:
          kernel_branch: "v7.0.4"
          kernel_config: "test-kernel-extra.config"
          custom_label: "test"

      - name: Verify output
        run: |
          ls -lh "${{ steps.build.outputs.image_path }}"
          qemu-img info "${{ steps.build.outputs.image_path }}"
